export const PEOPLE={maya:'Maya Chen',jordan:'Jordan Lee',sam:'Sam Rivera',alex:'Alex Morgan'};
export const date=(day,time)=>`2026-10-${String(day).padStart(2,'0')}T${time}:00-04:00`;
const shift=(id,day,start,end,job='harbor',owner='maya')=>({id,job,owner,start:date(day,start),end:date(day,end),role:'Barista',version:1,updated:date(11,'18:00')});
export function seed(){return {schema:1,revision:0,now:date(12,'06:00'),onboarded:true,jobs:{juniper:'Juniper Bistro'},buffers:{'harbor:juniper':30,'juniper:harbor':30},members:{maya:true,jordan:true,sam:true},shifts:[shift('h1',12,'09:00','15:00'),shift('p1',12,'14:30','20:00','juniper'),shift('h2',14,'08:00','14:00'),shift('p2',15,'16:00','21:00','juniper'),shift('h3',16,'09:00','15:00'),shift('p3',17,'15:00','21:00','juniper'),shift('j1',13,'08:00','14:00','harbor','jordan'),shift('s1',15,'09:00','15:00','harbor','sam')],requests:[],reminders:[],next:1};}
export const millis=x=>new Date(x).getTime();
export const active=r=>['Open','Awaiting approval'].includes(r.status);
export const cutoff=s=>millis(s.start)-7200000;
export const overlap=(a,b)=>millis(a.start)<millis(b.end)&&millis(b.start)<millis(a.end);
export function conflicts(state,owner){const ss=state.shifts.filter(s=>s.owner===owner).sort((a,b)=>millis(a.start)-millis(b.start));let result=[];for(let i=0;i<ss.length;i++)for(let j=i+1;j<ss.length;j++){const a=ss[i],b=ss[j];if(overlap(a,b)){result.push({a,b,type:'overlap',minutes:Math.round((Math.min(millis(a.end),millis(b.end))-Math.max(millis(a.start),millis(b.start)))/60000)});}else if(j===i+1&&a.job!==b.job){const gap=(millis(b.start)-millis(a.end))/60000;const buffer=state.buffers[`${a.job}:${b.job}`];if(gap<180){if(buffer==null)result.push({a,b,type:'unknown',minutes:gap});else if(gap<buffer)result.push({a,b,type:'travel',minutes:gap,buffer});}}}return result;}
export function eligible(state,shift,who){if(!state.members[who]||who===shift.owner)return false;const trial={...state,shifts:[...state.shifts.filter(s=>s.id!==shift.id),{...shift,owner:who}]};return !conflicts(trial,who).some(c=>(c.a.id===shift.id||c.b.id===shift.id)&&c.type!=='unknown');}
function log(s,r,text){r.events.push({text,at:s.now});}
export function expire(s){for(const r of s.requests)if(active(r)){const sh=s.shifts.find(x=>x.id===r.shiftId);if(!sh||sh.version!==r.version){r.status='Cancelled';r.offers.forEach(o=>{if(o.status==='Active')o.status='Invalidated'});log(s,r,'Shift changed. Previous offers are no longer valid.');}else if(millis(s.now)>=cutoff(sh)){r.status='Expired';r.offers.forEach(o=>{if(o.status==='Active')o.status='Expired'});log(s,r,'Deadline passed without approval. Original assignment remains.');}}return s;}
export function transition(state,action){const s=structuredClone(state);expire(s);const who=action.actor;const sh=s.shifts.find(x=>x.id===action.shiftId);const r=s.requests.find(x=>x.id===action.requestId);const fail=x=>{throw new Error(x)};const req=()=>{if(!r||!active(r))fail('This request is no longer active. Refresh the request and try again.');return s.shifts.find(x=>x.id===r.shiftId)};
if(action.type==='request'){if(!sh||sh.job!=='harbor'||sh.owner!==who)fail('Only your participating-workplace shifts can be offered.');if(millis(s.now)>=cutoff(sh))fail('The coverage deadline has passed. Contact your manager.');if(s.requests.some(x=>x.shiftId===sh.id&&active(x)))fail('A request is already active for this shift.');s.requests.push({id:'r'+s.next++,shiftId:sh.id,version:sh.version,requester:who,status:'Open',note:action.note||'',offers:[],events:[{text:'Coverage requested. Original worker remains assigned.',at:s.now}]});}
if(action.type==='volunteer'){const x=req();if(!action.confirm)fail('Please confirm your availability.');if(!eligible(s,x,who))fail('This shift is unavailable to you or conflicts with your saved schedule.');if(r.offers.some(o=>o.user===who&&o.status==='Active'))fail('Your offer is already awaiting review.');r.offers.push({id:'o'+s.next++,user:who,status:'Active'});r.status='Awaiting approval';log(s,r,'A coworker volunteered. Manager approval is still needed.');}
if(['withdraw','reject'].includes(action.type)){req();const o=r.offers.find(x=>x.id===action.offerId&&x.status==='Active');if(!o)fail('This offer is no longer active.');if(action.type==='reject'&&who!=='alex'||action.type==='withdraw'&&who!==o.user)fail('You cannot change this offer.');o.status=action.type==='reject'?'Rejected':'Withdrawn';r.status=r.offers.some(o=>o.status==='Active')?'Awaiting approval':'Open';log(s,r,action.type==='reject'?'Manager declined an offer. Coverage is not confirmed.':'A volunteer withdrew. Coverage is not confirmed.');}
if(action.type==='approve'){const x=req();if(who!=='alex')fail('Manager approval is required.');const o=r.offers.find(o=>o.id===action.offerId&&o.status==='Active');if(!o||x.version!==r.version||!eligible(s,x,o.user))fail('This offer changed or is no longer available. Refresh before approving.');x.owner=o.user;x.version++;x.updated=s.now;r.status='Covered';r.replacement=o.user;r.offers.forEach(p=>p.status=p.id===o.id?'Selected':p.status==='Active'?'Not selected':p.status);log(s,r,`Coverage confirmed. ${PEOPLE[o.user]} is now assigned.`);}
if(action.type==='cancel'){req();if(who!==r.requester&&who!=='alex')fail('Only the requester or manager can cancel.');r.status='Cancelled';r.offers.forEach(o=>{if(o.status==='Active')o.status='Cancelled'});log(s,r,'Request cancelled. Original assignment remains.');}
if(action.type==='savePrivate'){if(who==='alex')fail('Managers cannot edit private schedules.');const x=action.shift;if(!Number.isFinite(millis(x.start))||millis(x.end)<=millis(x.start))fail('End date and time must be after the start.');const old=s.shifts.find(y=>y.id===x.id);if(old&&(old.owner!==who||old.job==='harbor'))fail('This shift cannot be edited here.');s.jobs[x.job]=action.jobName;s.shifts=s.shifts.filter(y=>y.id!==x.id);s.shifts.push({...x,owner:who,version:(old?.version||0)+1,updated:s.now});if(action.buffer!==undefined)s.buffers['harbor:'+x.job]=action.buffer;}
if(action.type==='deletePrivate'){if(!sh||sh.owner!==who||sh.job==='harbor')fail('This shift cannot be deleted.');s.shifts=s.shifts.filter(x=>x.id!==sh.id);}
if(action.type==='remind'){s.reminders.push({owner:who,shiftId:action.shiftId});}
s.revision++;return s;}
export function localInstant(day,time,zone='America/New_York',choice=''){const wall=Date.parse(`${day}T${time}:00Z`);if(!Number.isFinite(wall))throw new Error('Enter a valid date and time.');let matches=[];const f=new Intl.DateTimeFormat('sv-SE',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});for(let off=-14*60;off<=14*60;off+=15){const t=wall-off*60000;if(f.format(new Date(t)).replace(' ','T')===`${day}T${time}`)matches.push(new Date(t).toISOString());}if(!matches.length)throw new Error('This time does not exist because the clocks change. Choose another time.');if(matches.length>1&&!choice)throw new Error('This time occurs twice when clocks change. Choose the earlier or later occurrence.');return choice==='later'?matches.at(-1):matches[0];}
